---
Name: iqminisitepages
---
Page:
  extensions:
    - IQnection\Minisite\PageExtension
PageController:
  extensions:
    - IQnection\Minisite\PageControllerExtension
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - iqnection-pages/minisitepage
    - iqnection-pages/basepages
---