---
Name: iqminisitepages
---
Page:
  extensions:
    - IqMinisitePageExtension
PageController:
  extensions:
    - IqMinisitePageControllerExtension
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - iqnection-pages/minisitepage
    - iqnection-pages/basepages
---